const characters = [
  // SSR (1x)
  {
    name: 'Verdant Angel',
    src: 'ssr_wood.png',
    properties: {
      grade: 'SSR',
      attribute: 'wood',
      hp: 1500,
      skillTurn: 3,
      attack: 500,
      attackMode: 'multi',
      defend: 400,
      skills: "Nature's Embrace",
    },
  },

  // SR (2x)
  {
    name: 'Flame Sprite',
    src: 'sr_fire.png',
    properties: {
      grade: 'SR',
      attribute: 'fire',
      hp: 1000,
      skillTurn: 4,
      attack: 350,
      attackMode: 'single',
      defend: 300,
      skills: 'Fire Dance',
    },
  },
  {
    name: 'Azure Angel',
    src: 'sr_water.png',
    properties: {
      grade: 'SR',
      attribute: 'water',
      hp: 950,
      skillTurn: 4,
      attack: 330,
      attackMode: 'single',
      defend: 320,
      skills: "Water's Blessing",
    },
  },

  // R (5x)
  {
    name: 'Luminous Guardian',
    src: 'r_light1.png',
    properties: {
      grade: 'R',
      attribute: 'light',
      hp: 700,
      skillTurn: 4,
      attack: 250,
      attackMode: 'single',
      defend: 200,
      skills: 'Radiant Shield',
    },
  },
  {
    name: 'Mystic Guardian',
    src: 'r_dark1.png',
    properties: {
      grade: 'R',
      attribute: 'dark',
      hp: 750,
      skillTurn: 5,
      attack: 270,
      attackMode: 'single',
      defend: 210,
      skills: 'Shadow Strike',
    },
  },
  {
    name: 'Woodling Warrior',
    src: 'r_wood1.png',
    properties: {
      grade: 'R',
      attribute: 'wood',
      hp: 720,
      skillTurn: 5,
      attack: 240,
      attackMode: 'single',
      defend: 220,
      skills: 'Rooted Strike',
    },
  },
  {
    name: 'Fire Blossom',
    src: 'r_fire1.png',
    properties: {
      grade: 'R',
      attribute: 'fire',
      hp: 750,
      skillTurn: 4,
      attack: 260,
      attackMode: 'multi',
      defend: 210,
      skills: 'Flame Bloom',
    },
  },
  {
    name: 'Water Sprite',
    src: 'r_water1.png',
    properties: {
      grade: 'R',
      attribute: 'water',
      hp: 730,
      skillTurn: 4,
      attack: 220,
      attackMode: 'single',
      defend: 250,
      skills: 'Bubble Shield',
    },
  },

  // N (5x)
  {
    name: 'Cute Green Slime',
    src: 'n_slime1.png',
    properties: {
      grade: 'N',
      attribute: 'wood',
      hp: 300,
      skillTurn: 5,
      attack: 100,
      attackMode: 'single',
      defend: 100,
      skills: 'Slime Splash',
    },
  },
  {
    name: 'Cheerful Blue Slime',
    src: 'n_slime2.png',
    properties: {
      grade: 'N',
      attribute: 'water',
      hp: 320,
      skillTurn: 5,
      attack: 120,
      attackMode: 'single',
      defend: 90,
      skills: 'Water Slime',
    },
  },
  {
    name: 'Fluffy Red Slime',
    src: 'n_slime3.png',
    properties: {
      grade: 'N',
      attribute: 'fire',
      hp: 290,
      skillTurn: 5,
      attack: 110,
      attackMode: 'single',
      defend: 95,
      skills: 'Fire Burst',
    },
  },
  {
    name: 'Radiant Yellow Slime',
    src: 'n_slime4.png',
    properties: {
      grade: 'N',
      attribute: 'light',
      hp: 310,
      skillTurn: 5,
      attack: 115,
      attackMode: 'single',
      defend: 100,
      skills: 'Light Bubbles',
    },
  },
  {
    name: 'Dark Sticky Slime',
    src: 'n_slime5.png',
    properties: {
      grade: 'N',
      attribute: 'dark',
      hp: 280,
      skillTurn: 5,
      attack: 90,
      attackMode: 'single',
      defend: 110,
      skills: 'Shadow Goo',
    },
  },
]
export default characters
